#Environment
st:
  ENVIRONMENT: https://gorest.co.in/


#  st:
#    ENVIRONMENT: https://naveenautomationlabs.com/opencart/index.php?route=common/home
#    EMAIl_ADDRESS: amandahaydaw@yahoo.com.au
#    PASSWORD: yahoo123@